export const enum ErrorCode {
  BOARD_NOT_FOUND = 'BOARD_NOT_FOUND',
  INVALID_COLUMN_NAME = 'INVALID_COLUMN_NAME',
  INVALID_CARD_NAME = 'INVALID_CARD_NAME',
  DUPLICATED_CARD_ERROR = 'DUPLICATED_CARD_ERROR',
  COLUMN_NOT_FOUND = 'COLUMN_NOT_FOUND',
}
