// Generated by ts-to-zod
import { z } from "zod";

export const AddColumnTypeSchema = z.literal("AddColumn");

export const AddColumnSchema = z.object({
  type: AddColumnTypeSchema,
  id: z.string(),
  name: z.string(),
});

export const CardCreatedTypeSchema = z.literal("CardCreatedType");

export const ColumnAddedTypeSchema = z.literal("ColumnAdded");

export const CreateCardTypeSchema = z.literal("CreateCard");

export const CreateCardSchema = z.object({
  type: CreateCardTypeSchema,
  name: z.string(),
});

export const ColumnAddedSchema = z.object({
  type: ColumnAddedTypeSchema,
  name: z.string(),
});

export const CardCreatedSchema = z.object({
  type: CardCreatedTypeSchema,
  name: z.string(),
});

export const BoardCommandSchema = z.union([AddColumnSchema, CreateCardSchema]);

export const BoardEventSchema = z.union([ColumnAddedSchema, CardCreatedSchema]);
