// Generated by ts-to-zod
import { z } from "zod";

const AddColumnTypeSchema = z.literal("AddColumn");

const AddColumnSchema = z.object({
  type: AddColumnTypeSchema,
  id: z.string(),
  name: z.string(),
});

const CardCreatedTypeSchema = z.literal("CardCreatedType");

const ColumnAddedTypeSchema = z.literal("ColumnAdded");

const CreateCardTypeSchema = z.literal("CreateCard");

const CreateCardSchema = z.object({
  type: CreateCardTypeSchema,
  name: z.string(),
});

const ColumnAddedSchema = z.object({
  type: ColumnAddedTypeSchema,
  name: z.string(),
});

const CardCreatedSchema = z.object({
  type: CardCreatedTypeSchema,
  name: z.string(),
});

const BoardCommandSchema = z.union([AddColumnSchema, CreateCardSchema]);

const BoardEventSchema = z.union([ColumnAddedSchema, CardCreatedSchema]);
